USE book_store;
GO

-- #: acessível só nessa consulta/conexão

CREATE TABLE #CLIENT_CONSUMED (ID SMALLINT IDENTITY (1, 1) UNIQUE NOT NULL, ID_CLIENT SMALLINT NOT NULL, TOTAL_CONSUMED MONEY NOT NULL);

SELECT * FROM #CLIENT_CONSUMED;

-- ##: acessível em todas as consultas, enquanto durar a conexão

CREATE TABLE ##TOP_BOOKS_SALES (ID SMALLINT IDENTITY (1, 1) UNIQUE NOT NULL, ID_BOOK SMALLINT NOT NULL, TOTAL_SALES MONEY NOT NULL);

SELECT * FROM ##TOP_BOOKS_SALES;

-- @: tabela declarada como variável, acessível em um bloco. Declaração similar à criação.

DECLARE @DATE_CREATED DATE;
DECLARE @BOOK TABLE (NAME VARCHAR (100), AUTHOR VARCHAR(100), CATEGORY VARCHAR(100), DATE DATE DEFAULT GETDATE());

-- Inserir

INSERT INTO @BOOK ([NAME], [AUTHOR], [CATEGORY], [DATE]) VALUES ('Harry Potter', 'JK Rowlling', 'Ficção', '2020-12-31');

SET @DATE_CREATED = '2020-12-31';

IF (SELECT COUNT(*) FROM @BOOK WHERE DATE = @DATE_CREATED) > 0 SELECT NAME, AUTHOR, CATEGORY FROM @BOOK WHERE DATE = @DATE_CREATED;
ELSE PRINT 'Nenhum livro foi criado nessa data';

