USE book_store;
GO

-- Criar trigger: quantidade de livros em cada categoria

CREATE TRIGGER TG_CATEGORY_BOOK ON book AFTER INSERT, UPDATE, DELETE AS 
BEGIN

	SELECT CATEGORY, COUNT(*) AS COUNT_CATEGORY FROM book GROUP BY CATEGORY;

END;

CREATE TRIGGER TG_CATEGORY_BOOKS ON book AFTER INSERT, UPDATE, DELETE AS 
BEGIN

	SELECT CATEGORY, COUNT(*) AS COUNT_CATEGORY FROM book GROUP BY CATEGORY;

END;

-- Deletar trigeer

DROP TRIGGER IF EXISTS TG_CATEGORY_BOOK;

-- Criar trigger: soma total de livros por mês

CREATE TRIGGER TG_SUM_SALES_BOOKS_MONTH ON books_sales AFTER INSERT, UPDATE, DELETE AS
BEGIN

	SELECT SUM(TOTAL_SALES_BOOK) AS TOTAL_SALES_BOOKS_MONTH FROM [VM_TOTAL_SALES_MONTH]; 

END;

-- Criar trigger: soma total de consumo por cliente e por mês

CREATE TRIGGER TG_SUM_SALES_CLIENT_MONTH ON books_sales AFTER INSERT, UPDATE, DELETE AS
BEGIN

	SELECT * FROM [VW_TOTAL_SALES_MONTH_CLIENT]; 

END;