-- COUNT usando WHERE

USE book_store;
GO

SELECT SUM(ID) AS SOMA_ID, MIN(YEAR(DATE_CREATED)) AS MIN_ANO_CRIACAO, MAX(MONTH(DATE_CREATED)) AS MAX_MES_CRIACAO, AVG(DAY(DATE_CREATED)) AS MEDIA_DIAS_CRIACAO, COUNT(ID) AS NUMERO_LIVROS FROM book WHERE ID > 6;