-- Comandos tabela

-- Criar tabela: campo, tipo, null/not null, pk...

CREATE TABLE client (ID SMALLINT IDENTITY UNIQUE NOT NULL, CPF VARCHAR(11) NOT NULL, NAME VARCHAR(100) NOT NULL, PHONE_NUMBER VARCHAR(50) NOT NULL, FIRST_BUY BIT);

CREATE TABLE book (ID SMALLINT IDENTITY UNIQUE NOT NULL, NAME VARCHAR (100) NOT NULL, AUTHOR VARCHAR(100) NOT NULL, CATEGORY VARCHAR(100) NOT NULL);

-- Deletar tabela

DROP TABLE IF EXISTS book;