-- Comandos tabela

-- Criar tabela: campo, tipo, null/not null, pk, fk...

CREATE TABLE client (ID SMALLINT IDENTITY UNIQUE NOT NULL, ID_BOOK SMALLINT NOT NULL, CPF VARCHAR(11) NOT NULL, NAME VARCHAR(100) NOT NULL, PHONE_NUMBER VARCHAR(50) NOT NULL, FIRST_BUY BIT, CONSTRAINT FK_ID_BOOK FOREIGN KEY (ID_BOOK) REFERENCES BOOK(ID));

CREATE TABLE book (ID SMALLINT IDENTITY UNIQUE NOT NULL, NAME VARCHAR (100) NOT NULL, AUTHOR VARCHAR(100) NOT NULL, CATEGORY VARCHAR(100) NOT NULL);

CREATE TABLE books_prices (ID SMALLINT IDENTITY UNIQUE NOT NULL, ID_BOOK SMALLINT NOT NULL, PRICE FLOAT NOT NULL, CONSTRAINT FK_BOOK_ID FOREIGN KEY (ID_BOOK) REFERENCES BOOK(ID));

-- Deletar tabela

DROP TABLE IF EXISTS book;

DROP TABLE IF EXISTS client;