-- VIEW. Alter = replace

USE book_store;
GO

CREATE OR ALTER VIEW [VW_BOOK] AS SELECT [NAME], [AUTHOR] FROM [BOOK];

SELECT * FROM VW_BOOK;

-- VIEW usando WHERE

CREATE OR ALTER VIEW [VW_CLIENT] AS SELECT [NAME], [CPF], [PHONE_NUMBER] FROM [CLIENT] WHERE [NAME] LIKE '%Silva';

SELECT * FROM [VW_CLIENT];